apiVersion: v1
kind: Secret
metadata:
  name: site-secrets
type: Opaque
stringData:
  AzureAd__Instance: https://login.microsoftonline.com/
  AzureAd__Domain: example.onmicrosoft.com
  AzureAd__TenantId: replace-me
  AzureAd__ClientId: replace-me
  AzureAd__CallbackPath: /signin-oidc
  ConnectionStrings__DefaultConnection: Host=replace-me;Port=5432;Database=replace-me-app;Username=replace-me;Password=replace-me
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me
  OPENAI_API_KEY: replace-me

