apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - wiseravenshare-wiseravenshare.com
      secretName: wiseravenshare-tls
  rules:
    - host: wiseravenshare-wiseravenshare.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
