namespace Wiseravenshare.Server.Entities;

/// <summary>
/// Represents a device connected to a Podcast Studio session.
/// Tracks device identity, token expiry, and last heartbeat.
/// </summary>
public class PodcastSessionDevice
{
    /// <summary>Device ID (generated by client, persisted in local storage)</summary>
    public string Id { get; set; } = null!;

    /// <summary>Session this device is connected to</summary>
    public string SessionId { get; set; } = null!;

    /// <summary>User on this device</summary>
    public string UserId { get; set; } = null!;

    /// <summary>Device name/identifier (e.g., "John's Laptop", "Studio Room PC", "Sarah's iPhone")</summary>
    public string DeviceName { get; set; } = null!;

    /// <summary>Device type: "web", "mobile", "desktop"</summary>
    public string DeviceType { get; set; } = "web";

    /// <summary>User agent (browser/app identifier)</summary>
    public string? UserAgent { get; set; }

    /// <summary>When this device joined the session</summary>
    public DateTime JoinedAt { get; set; } = DateTime.UtcNow;

    /// <summary>When this device last sent a heartbeat (ping)</summary>
    public DateTime? LastHeartbeatAt { get; set; }

    /// <summary>
    /// Auth token expiry time for this device.
    /// Client auto-refreshes token before expiry via /api/auth/refresh.
    /// Server does not interrupt auth; instead, token refresh is silent.
    /// </summary>
    public DateTime? TokenExpiresAt { get; set; }

    /// <summary>Device is actively connected and sending heartbeats (not stale)</summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Device-specific state (JSON): local recording buffer, unsaved edits, etc.
    /// NOT shared across devices; each device maintains its own state.
    /// </summary>
    public string? LocalStateJson { get; set; }

    /// <summary>Navigation: Session</summary>
    public virtual PodcastSession? Session { get; set; }
}
