namespace Wiseravenshare.Server.DTOs;

/// <summary>Request: Create a new Podcast Studio session</summary>
public class CreatePodcastSessionRequest
{
    public string TeamId { get; set; } = null!;
    public string AccessScope { get; set; } = "team"; // "team" or "device-restricted"
    public string? AllowedUserIds { get; set; } // Comma-delimited, required if access_scope = device-restricted
}

/// <summary>Request: Join or refresh device in an active session</summary>
public class RegisterDeviceRequest
{
    public string SessionId { get; set; } = null!;
    public string DeviceId { get; set; } = null!; // Generated by client, stored in local storage
    public string DeviceName { get; set; } = null!; // "John's Laptop", "Studio Room PC", etc.
    public string DeviceType { get; set; } = "web"; // "web", "mobile", "desktop"
}

/// <summary>Request: Sync state from a device</summary>
public class SyncStateRequest
{
    public string SessionId { get; set; } = null!;
    public string DeviceId { get; set; } = null!;
    public string? LocalStateJson { get; set; }
}

/// <summary>Request: Send heartbeat to keep device alive</summary>
public class HeartbeatRequest
{
    public string SessionId { get; set; } = null!;
    public string DeviceId { get; set; } = null!;
}

/// <summary>Response: Podcast session info</summary>
public class PodcastSessionDto
{
    public string Id { get; set; } = null!;
    public string TeamId { get; set; } = null!;
    public string Status { get; set; } = null!; // "active", "closing", "closed"
    public string AccessScope { get; set; } = null!;
    public DateTime CreatedAt { get; set; }
    public DateTime? ClosedAt { get; set; }
    public object? SessionState { get; set; }
    public int StateVersion { get; set; }
    public List<PodcastSessionDeviceDto> Devices { get; set; } = new();
}

/// <summary>Response: Device in a session</summary>
public class PodcastSessionDeviceDto
{
    public string Id { get; set; } = null!;
    public string UserId { get; set; } = null!;
    public string DeviceName { get; set; } = null!;
    public string DeviceType { get; set; } = null!;
    public DateTime JoinedAt { get; set; }
    public DateTime? LastHeartbeatAt { get; set; }
    public double TokenExpiresInSeconds { get; set; }
    public bool IsActive { get; set; }
}

/// <summary>Response: State sync result</summary>
public class SyncStateResponse
{
    public string SessionId { get; set; } = null!;
    public object? SessionState { get; set; }
    public int StateVersion { get; set; }
    public List<PodcastSessionDeviceDto> ActiveDevices { get; set; } = new();
    public double TokenExpiresInSeconds { get; set; }
}
