using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using Wiseravenshare.Server.Entities;

namespace Wiseravenshare.Server.Entities.Personalization;

public class ContentTag : BaseEntity
{
    [MaxLength(255)]
    public string Name { get; set; } = string.Empty;

    [MaxLength(500)]
    public string? Description { get; set; }

    public TagCategory Category { get; set; } = TagCategory.General;
    public TagType Type { get; set; } = TagType.User;
    public int Weight { get; set; } = 1;
    public int UsageCount { get; set; }
    public JsonDocument? Synonyms { get; set; }
    public JsonDocument? RelatedTags { get; set; }
    public JsonDocument? Embedding { get; set; }

    // Navigation Properties
    public virtual ICollection<ContentTagMapping> Mappings { get; set; } = new List<ContentTagMapping>();
}

public enum TagCategory
{
    General,
    Topic,
    Genre,
    Mood,
    Era,
    Location,
    Activity,
    LifeEvent,
    Profession,
    Skill
}

public enum TagType
{
    User,
    System,
    AI,
    Collaborative
}

public class ContentTagMapping : BaseEntity
{
    public Guid ContentTagId { get; set; }
    public string TargetType { get; set; } = string.Empty;
    public Guid TargetId { get; set; }
    public int Confidence { get; set; } = 100;
    public bool IsAutoGenerated { get; set; }
    public Guid? GeneratedBy { get; set; }

    // Navigation Properties
    public virtual ContentTag Tag { get; set; } = null!;
}
