using System.ComponentModel.DataAnnotations;
using System.Text.Json;

namespace Wiseravenshare.Server.Entities.Personalization;

// ─── User Profile ─────────────────────────────────────────────────────────────
public class UserPersonalizationProfile : BaseEntity
{
    public Guid UserId { get; set; }

    // Demographic
    [MaxLength(20)]  public string? AgeRange    { get; set; }
    [MaxLength(20)]  public string? Gender       { get; set; }
    [MaxLength(255)] public string? Location     { get; set; }
    [MaxLength(10)]  public string? CountryCode  { get; set; }  // ISO-3166 e.g. "US"
    [MaxLength(20)]  public string? RegionCode   { get; set; }  // e.g. "US-NY"
    [MaxLength(50)]  public string? Timezone     { get; set; }
    [MaxLength(255)] public string? Occupation   { get; set; }

    // Languages (JSON array of BCP-47 codes)
    public string? Languages { get; set; }

    // Life stage
    public UserLifeStage LifeStage { get; set; } = UserLifeStage.Unknown;
    public string? LifeInterests      { get; set; }  // JSON string[]
    public string? CurrentGoals       { get; set; }  // JSON string[]
    public string? LifeEvents         { get; set; }  // JSON string[]

    // Behavioral preferences
    public string? FavoriteGenres        { get; set; }  // JSON string[]
    public string? FavoriteTopics        { get; set; }  // JSON string[]
    public string? FavoriteCreators      { get; set; }  // JSON string[]
    public string? PreferredContentTypes { get; set; }  // JSON string[]

    // Temporal patterns
    public string? ActiveHours { get; set; }  // JSON int[]  (0-23)
    public string? ActiveDays  { get; set; }  // JSON int[]  (0=Sun..6)
    public int AverageSessionDurationSeconds { get; set; }
    public DateTime? LastActiveAt { get; set; }

    // Learned vectors (lightweight key:weight JSON dicts)
    public string? EmbeddingVector    { get; set; }  // JSON dict<string,float>
    public string? BehavioralPatterns { get; set; }  // JSON dict<string,float>

    public virtual User User { get; set; } = null!;
}

public enum UserLifeStage
{
    Unknown, Student, EarlyCareer, MidCareer, LateCareer, Retired, Parent, EmptyNester
}

// ─── Interaction Tracking ─────────────────────────────────────────────────────
public class UserInteractionEvent : BaseEntity
{
    public Guid UserId { get; set; }

    public InteractionEventType Type { get; set; }

    [MaxLength(64)]   public string  TargetType     { get; set; } = string.Empty;
    public Guid?      TargetId       { get; set; }
    [MaxLength(500)]  public string? TargetTitle    { get; set; }
    [MaxLength(255)]  public string? TargetCategory { get; set; }
    [MaxLength(1000)] public string? TargetTags     { get; set; }

    public int? EngagementScore { get; set; }
    public int? DurationSeconds { get; set; }

    [MaxLength(64)]  public string? DeviceType  { get; set; }
    [MaxLength(10)]  public string? CountryCode { get; set; }
    [MaxLength(20)]  public string? RegionCode  { get; set; }

    public virtual User User { get; set; } = null!;
}

public enum InteractionEventType
{
    View, Like, Dislike, Comment, Share, Bookmark,
    Follow, Search, Play, Skip, Complete, Dismiss, Rate
}

// ─── Content Tag ─────────────────────────────────────────────────────────────
public class PersonalizationTag : BaseEntity
{
    [MaxLength(255)] public string  Name        { get; set; } = string.Empty;
    [MaxLength(500)] public string? Description { get; set; }

    public PersonalizationTagCategory Category { get; set; } = PersonalizationTagCategory.General;
    public int Weight     { get; set; } = 1;
    public int UsageCount { get; set; }

    public string? Synonyms    { get; set; }  // JSON string[]
    public string? RelatedTags { get; set; }  // JSON string[]

    public virtual ICollection<PersonalizationTagMapping> Mappings { get; set; } = new List<PersonalizationTagMapping>();
}

public enum PersonalizationTagCategory
{
    General, Topic, Genre, Mood, Era, Location, Activity, LifeEvent, Profession, Skill
}

public class PersonalizationTagMapping : BaseEntity
{
    public Guid     TagId      { get; set; }
    [MaxLength(64)] public string TargetType { get; set; } = string.Empty;
    public Guid     TargetId   { get; set; }
    public int      Confidence { get; set; } = 100;
    public bool     IsAutoGenerated { get; set; }

    public virtual PersonalizationTag Tag { get; set; } = null!;
}

// ─── Regional Trend Snapshot ─────────────────────────────────────────────────
public class RegionalTrendSnapshot : BaseEntity
{
    [MaxLength(10)] public string CountryCode  { get; set; } = "GLOBAL";
    [MaxLength(20)] public string Category     { get; set; } = "General";

    // JSON: array of { topic:string, score:decimal, source:string }
    public string TopicsJson  { get; set; } = "[]";
    public DateTime SnapshotAt { get; set; } = DateTime.UtcNow;
    public DateTime ExpiresAt  { get; set; } = DateTime.UtcNow.AddHours(2);
}
