// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Wiseravenshare.Server.Infrastructure.Data;

#nullable disable

namespace Wiseravenshare.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916200301_FixCrawlerTableSchema")]
    partial class FixCrawlerTableSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Raw SQL migration - model unchanged.
        }
    }
}
