// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Wiseravenshare.Server.Infrastructure.Data;

#nullable disable

namespace Wiseravenshare.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916200300_AddCraftIntelligenceTables")]
    partial class AddCraftIntelligenceTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally empty - this is a raw SQL migration that doesn't modify the EF model.
            // The model is unchanged from the previous migration.
        }
    }
}
