// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Wiseravenshare.Server.Infrastructure.Data;

#nullable disable

namespace Wiseravenshare.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916200302_AddMissingColumnsRecovery")]
    partial class AddMissingColumnsRecovery
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
